version: 0.0
os: linux
files:
  - source: ./VijayJavaHelloWorld.war
    destination: /tmp/
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
    - location: scripts/undeploy_application.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/deploy_application.sh
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_application_is_running.sh
